### ISSUE TITLE
Sharing iP code quality feedback [for @camille-readbean]

### ISSUE THREAD

**Issue by soc-se-bot-blue** [camille-readbean/ip#5]
@camille-readbean We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

Example from [`src/main/java/me/ruibin/leto/tasklist/Task.java` lines `5-5`](https://github.com/camille-readbean/ip/blob/66360d3fb075b0c9af0effc129a3efdec410d591/src/main/java/me/ruibin/leto/tasklist/Task.java#L5..L5):

```java

    private boolean completed;

``` 

**Suggestion:** Follow the given naming convention for boolean variables/methods (e.g., use a boolean-sounding prefix).You may ignore the above if you think the name already follows the convention (the script can report false positives in some cases)

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/me/ruibin/leto/Leto.java` lines `23-26`](https://github.com/camille-readbean/ip/blob/66360d3fb075b0c9af0effc129a3efdec410d591/src/main/java/me/ruibin/leto/Leto.java#L23..L26):

```java

    /**
     * You should have your own function to generate a response to user input.
     * Replace this stub with your completed method.
     */

```

Example from [`src/main/java/me/ruibin/leto/parser/Parser.java` lines `40-45`](https://github.com/camille-readbean/ip/blob/66360d3fb075b0c9af0effc129a3efdec410d591/src/main/java/me/ruibin/leto/parser/Parser.java#L40..L45):

```java

    /**
     * Read user inputs and run the command.
     *
     * @param inputs String of the input
     * @return Result containing type, message and exception if any.
     */

```

Example from [`src/main/java/me/ruibin/leto/parser/Result.java` lines `30-35`](https://github.com/camille-readbean/ip/blob/66360d3fb075b0c9af0effc129a3efdec410d591/src/main/java/me/ruibin/leto/parser/Result.java#L30..L35):

```java

    /**
     * Method to append messages to current StringBuilder.
     *
     * @param message new message to be appended.
     * @return Appended message builder.
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message

possible problems in commit [`a45c8fb`](https://github.com/camille-readbean/ip/commit/a45c8fbf128f416b404d4f2535020c113b74916f):

```

Merge pull request #3 from camille-readbean/branch-A-Streams

Merge branch-A-Streams.
Modify Find to make use of Streams.
* FindCommand now use Stream and filter to search for the task with a keyword.

```

* body not wrapped at 72 characters: e.g., `* FindCommand now use Stream and filter to search for the task with a keyword.`
            

possible problems in commit [`51d6ed2`](https://github.com/camille-readbean/ip/commit/51d6ed2adf864599c99fb412ec22ddbd7795b75b):

```

Modify Find to make use of Streams

FindCommand now use Stream and filter to search for the task with a keyword.


```

* body not wrapped at 72 characters: e.g., `FindCommand now use Stream and filter to search for the task with a keyword.`
             

**Suggestion:** Follow the given [conventions for Git commit messages](https://se-education.org/guides/conventions/git.html) for _future_ commits (do not modify past commit messages as doing so will change the commit timestamp that we used to detect your commit timings).

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

----

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by camille-readbean** [comment]
Fixed in 1c793682099753012b025f756a351aa9852cbc10.
